baseURL = "https://hugo.gnome.no"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Home"

# theme as hugo module
#theme = "github.com/lxndrblz/anatole"
# theme as git submodule
theme = "anatole"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

[params]
  title = "Claus Guttesen"
  theme = "anatole"
  author = "Claus Guttesen"
  description = "Kald mig Claus"
  profilePicture = "profile-pic.png"
  doNotLoadAnimations = true # Animations are loaded by default
  custom_css = ["css/custom.css"]

[[params.socialIcons]]
  icon = "fab fa-github"
  title = "GitHub"
  url = "https://github.com/kometen/"
[[params.socialIcons]]
  icon = "fab fa-twitter"
  title = "Twitter"
  url = "https://twitter.com/kometen/"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "post"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"